import {
  LayoutDashboard,
  FolderKanban,
  Package,
  Users,
  Truck,
  HardHat,
  Sparkles,
  BarChart3,
  Bell,
  Settings,
  ClipboardList,
  Calendar,
  TrendingUp,
  FileCheck2,
  FileText,
  AlertTriangle,
  Camera,
  ShieldCheck,
  Brain,
  ShieldAlert,
  Bot,
  Warehouse,
  ReceiptText,
  PackageMinus,
  Trash2,
  UserCheck,
  Clock,
  DollarSign,
  Briefcase
} from 'lucide-react';
import { ROLES } from './roles';

export const NAVIGATION_ITEMS = [
  {
    title: 'Dashboard',
    path: '/dashboard',
    icon: LayoutDashboard,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SUPPLIER, ROLES.WORKER],
  },
  {
    title: 'Projects',
    path: '/projects',
    icon: FolderKanban,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR],
    children: [
      { title: 'All Projects', path: '/projects', icon: FolderKanban },
      { title: 'Project Details', path: '/projects/PRJ-001', icon: Briefcase },
      { title: 'Task Matrix', path: '/projects/tasks', icon: ClipboardList },
      { title: 'Timeline & Schedule', path: '/projects/timeline', icon: Calendar },
      { title: 'Overall Progress', path: '/projects/progress', icon: TrendingUp },
    ],
  },
  {
    title: 'Materials',
    path: '/materials',
    icon: Package,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SUPPLIER],
    children: [
      { title: 'Site Inventory', path: '/materials', icon: Warehouse },
      { title: 'Material Requests', path: '/materials/requests', icon: FileText },
      { title: 'Purchase Orders', path: '/materials/purchase-orders', icon: ReceiptText },
      { title: 'Goods Received (GRN)', path: '/materials/grn', icon: FileCheck2 },
      { title: 'Daily Consumption', path: '/materials/consumption', icon: PackageMinus },
      { title: 'Wastage Tracking', path: '/materials/wastage', icon: Trash2 },
    ],
  },
  {
    title: 'Labour',
    path: '/labour',
    icon: Users,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.WORKER],
    children: [
      { title: 'Workforce Roster', path: '/labour', icon: Users },
      { title: 'Daily Attendance', path: '/labour/attendance', icon: UserCheck },
      { title: 'Shift Management', path: '/labour/shifts', icon: Clock },
      { title: 'Wage & Payroll', path: '/labour/wages', icon: DollarSign },
      { title: 'Productivity Metrics', path: '/labour/productivity', icon: TrendingUp },
    ],
  },
  {
    title: 'Suppliers',
    path: '/suppliers',
    icon: Truck,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SUPPLIER],
  },
  {
    title: 'Site Operations',
    path: '/site/daily-reports',
    icon: HardHat,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR],
    children: [
      { title: 'Daily Site Logs', path: '/site/daily-reports', icon: FileText },
      { title: 'Issues & Hazards', path: '/site/issues', icon: AlertTriangle },
      { title: 'Progress Photos', path: '/site/photos', icon: Camera },
      { title: 'Safety Inspections', path: '/site/inspections', icon: ShieldCheck },
    ],
  },
  {
    title: 'Site Intelligence',
    path: '/intelligence',
    icon: Sparkles,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR],
    badge: 'AI Powered',
    children: [
      { title: 'Intelligence Overview', path: '/intelligence', icon: Sparkles },
      { title: 'Material Prediction', path: '/intelligence/predictions', icon: Brain },
      { title: 'Risk Radar', path: '/intelligence/risk', icon: ShieldAlert },
      { title: 'Actionable Advice', path: '/intelligence/recommendations', icon: TrendingUp },
      { title: 'AI Site Assistant', path: '/intelligence/assistant', icon: Bot },
    ],
  },
  {
    title: 'Analytics',
    path: '/analytics',
    icon: BarChart3,
    roles: [ROLES.ADMIN],
  },
  {
    title: 'Notifications',
    path: '/notifications',
    icon: Bell,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SUPPLIER, ROLES.WORKER],
    badgeCount: 3,
  },
  {
    title: 'Settings',
    path: '/settings',
    icon: Settings,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SUPPLIER, ROLES.WORKER],
  },
];
