import {
  LayoutDashboard,
  FolderKanban,
  Package,
  Users,
  Truck,
  HardHat,
  Sparkles,
  BarChart3,
  Bell,
  Settings,
  ClipboardList,
  Calendar,
  TrendingUp,
  FileCheck2,
  FileText,
  AlertTriangle,
  Camera,
  ShieldCheck,
  Brain,
  ShieldAlert,
  Bot,
  Warehouse,
  ReceiptText,
  PackageMinus,
  Trash2,
  UserCheck,
  Clock,
  ShoppingBag,
  History,
  DollarSign,
  Briefcase
} from 'lucide-react';
import { ROLES } from './roles';

export const NAVIGATION_ITEMS = [
  {
    title: 'Dashboard',
    path: '/dashboard',
    icon: LayoutDashboard,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SUPPLIER, ROLES.WORKER],
  },
  {
    title: 'Projects',
    path: '/projects',
    icon: FolderKanban,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR],
    children: [
      { title: 'All Projects', path: '/projects', icon: FolderKanban },
      { title: 'Project Details', path: '/projects/PRJ-001', icon: Briefcase },
      { title: 'Task Matrix', path: '/projects/tasks', icon: ClipboardList },
      { title: 'Timeline & Schedule', path: '/projects/timeline', icon: Calendar },
      { title: 'Overall Progress', path: '/projects/progress', icon: TrendingUp },
    ],
  },
  {
    title: 'Materials',
    path: '/materials',
    icon: Package,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SUPPLIER],
    children: [
      { title: 'Site Inventory', path: '/materials', icon: Warehouse },
      { title: 'Material Requests', path: '/materials/requests', icon: FileText },
      { title: 'Purchase Orders', path: '/materials/purchase-orders', icon: ReceiptText },
      { title: 'Goods Received (GRN)', path: '/materials/grn', icon: FileCheck2 },
      { title: 'Daily Consumption', path: '/materials/consumption', icon: PackageMinus },
      { title: 'Wastage Tracking', path: '/materials/wastage', icon: Trash2 },
    ],
  },
  {
    title: 'Labour',
    path: '/labour',
    icon: Users,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.WORKER],
    children: [
      { title: 'Labour Overview', path: '/labour', icon: Users },
      { title: 'Worker Directory', path: '/labour/workers', icon: Users },
      { title: 'Daily Attendance', path: '/labour/attendance', icon: UserCheck },
      { title: 'Workforce Allocation', path: '/labour/allocation', icon: Clock },
      { title: 'Productivity & OT', path: '/labour/productivity', icon: TrendingUp },
      { title: 'Labour Costs', path: '/labour/costs', icon: DollarSign },
    ],
  },
  {
    title: 'Suppliers',
    path: '/suppliers',
    icon: Truck,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SUPPLIER],
    children: [
      { title: 'Supplier Directory', path: '/suppliers', icon: Truck },
      { title: 'Supplier Performance', path: '/suppliers/performance', icon: TrendingUp },
    ],
  },
  {
    title: 'Procurement',
    path: '/procurement',
    icon: ShoppingBag,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SUPPLIER],
    children: [
      { title: 'Command Center', path: '/procurement', icon: LayoutDashboard },
      { title: 'Purchase Requests', path: '/procurement/requests', icon: FileText },
      { title: 'Purchase Orders', path: '/procurement/orders', icon: ReceiptText },
      { title: 'Deliveries', path: '/procurement/deliveries', icon: Truck },
      { title: 'Goods Received (GRN)', path: '/procurement/grn', icon: FileCheck2 },
      { title: 'Procurement History', path: '/procurement/history', icon: History },
    ],
  },
  {
    title: 'Site Operations',
    path: '/site',
    icon: HardHat,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.WORKER],
    children: [
      { title: 'Command Center', path: '/site', icon: LayoutDashboard },
      { title: 'Daily Report', path: '/site/daily-report', icon: FileText },
      { title: 'Work Progress', path: '/site/work-progress', icon: TrendingUp },
      { title: 'Site Issues', path: '/site/issues', icon: AlertTriangle },
      { title: 'Safety Management', path: '/site/safety', icon: ShieldCheck },
      { title: 'Site Activity', path: '/site/activity', icon: Clock },
      { title: 'Site Evidence', path: '/site/evidence', icon: Camera },
    ],
  },
  {
    title: 'Site Intelligence',
    path: '/intelligence',
    icon: Sparkles,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR],
    badge: 'Signals',
    children: [
      { title: 'Intelligence Overview', path: '/intelligence', icon: Sparkles },
      { title: 'Risk Radar', path: '/intelligence/risk-radar', icon: ShieldAlert },
      { title: 'Tomorrow Readiness', path: '/intelligence/readiness', icon: Calendar },
      { title: 'Actionable Insights', path: '/intelligence/insights', icon: TrendingUp },
    ],
  },
  {
    title: 'Analytics',
    path: '/analytics',
    icon: BarChart3,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR],
    children: [
      { title: 'Analytics Overview', path: '/analytics', icon: BarChart3 },
      { title: 'Project Analytics', path: '/analytics/projects', icon: FolderKanban },
      { title: 'Material Analytics', path: '/analytics/materials', icon: Package },
      { title: 'Labour Analytics', path: '/analytics/labour', icon: Users },
      { title: 'Procurement Analytics', path: '/analytics/procurement', icon: ShoppingBag },
      { title: 'Site Operations Analytics', path: '/analytics/site', icon: HardHat },
      { title: 'Cost Analytics', path: '/analytics/costs', icon: DollarSign },
    ],
  },
  {
    title: 'Notifications',
    path: '/notifications',
    icon: Bell,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SUPPLIER, ROLES.WORKER],
    badgeCount: 3,
  },
  {
    title: 'Settings',
    path: '/settings',
    icon: Settings,
    roles: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SUPPLIER, ROLES.WORKER],
  },
];
