import React from 'react';
import { PlaceholderPage } from '../../components/common/PlaceholderPage';
import { intelligenceTabs } from './IntelligenceOverviewPage';

export const RecommendationsPage = () => {
  return (
    <PlaceholderPage
      title="Automated Prescriptive Recommendations"
      subtitle="Actionable, dollar-quantified site optimizations generated by AI models."
      tabs={intelligenceTabs}
      phase="Phase 4"
    />
  );
};
